import Head from 'next/head'
import Link from 'next/link'

export default function Home({data}) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={"/tools/toolList"}>
        tools List
      </Link>
      {/* <p>
        { data.id }
      </p> */}
    </>
  )
}